# Generated by Django 3.2.2 on 2021-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading1', models.CharField(max_length=100)),
                ('Heading2', models.CharField(max_length=100)),
                ('Paragraph', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='Carousel/')),
            ],
            options={
                'verbose_name_plural': 'Carousel',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=100)),
                ('Review', models.TextField(max_length=100)),
                ('Image', models.FileField(upload_to='Review/')),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Text', models.TextField(max_length=100)),
                ('Image', models.FileField(upload_to='Service/')),
            ],
            options={
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
                ('Youtube', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVICES', models.CharField(max_length=100)),
                ('HAPPY_CLIENTS', models.CharField(max_length=100)),
                ('PEOPLE_LOVED', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
            },
        ),
    ]
