# Generated by Django 3.2.2 on 2021-05-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_carousel_review_service_socialmedia_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Time', models.DateTimeField()),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_app.package')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
    ]
