# Generated by Django 3.2.2 on 2021-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutText', models.TextField()),
                ('AboutPoint1', models.CharField(max_length=100)),
                ('AboutPoint2', models.CharField(max_length=100)),
                ('AboutPoint3', models.CharField(max_length=100)),
                ('About_Picture', models.FileField(upload_to='AboutImage/')),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=100)),
                ('About', models.CharField(max_length=100)),
                ('Picture', models.FileField(upload_to='AboutImage/')),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
                ('Facebook', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social Media'},
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='Image',
        ),
    ]
