# Generated by Django 3.2.2 on 2021-05-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0004_auto_20210515_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_Picture',
            field=models.FileField(upload_to='AboutImage'),
        ),
        migrations.AlterField(
            model_name='review',
            name='Image',
            field=models.FileField(upload_to='Review'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Image',
            field=models.FileField(upload_to='Service'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Picture',
            field=models.FileField(upload_to='Team'),
        ),
    ]
