# Generated by Django 3.2.2 on 2021-05-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0009_auto_20210515_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
