# Generated by Django 3.2.2 on 2021-05-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0010_delete_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='HAPPY_CLIENTS',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='PEOPLE_LOVED',
            new_name='Number',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='SERVICES',
        ),
    ]
