# Generated by Django 3.2.2 on 2021-05-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0013_auto_20210515_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='About_Picture',
            field=models.FileField(upload_to='About_Image/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Picture',
            field=models.FileField(upload_to='Team/'),
        ),
    ]
