# Generated by Django 3.2.2 on 2021-05-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0014_auto_20210516_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='About_Picture',
        ),
        migrations.AddField(
            model_name='about',
            name='Picture',
            field=models.FileField(default='timezone.now', upload_to='Team/'),
            preserve_default=False,
        ),
    ]
