# Generated by Django 3.2.2 on 2021-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0015_auto_20210516_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Time',
            field=models.CharField(max_length=100),
        ),
    ]
