# Generated by Django 3.2.2 on 2021-05-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0016_alter_reservation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Message',
            field=models.TextField(default='helle'),
            preserve_default=False,
        ),
    ]
